SQLALCHEMY_DATABASE_URI = "mysql+pymysql://root:20020316@localhost:3306/breadshop"
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_POOL_SIZE = 10
SQLALCHEMY_POOL_TIMEOUT = 30
SQLALCHEMY_POOL_RECYCLE = 1800
